server:
  port: 80


spring:
  application:
    name: cloud-consumers-order

eureka:
  client:
    register-with-eureka: true  #注册入eureka
    fetch-registry: true  #是否从eureka抓取已有注册信息。集群为true可配合ribbon使用负载均衡
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版