server:
  port: 83


spring:
  application:
    name: nacos-payment-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

#消费者访问得微服务名称
server-url:
  service: http://nacos-payment-provider